// Built-in APP lines (bootstrap). Runtime list may be overridden via [LineRepository].
import 'package:flutter/foundation.dart';

class LineConfig {
  const LineConfig({
    required this.id,
    required this.name,
    required this.label,
    required this.host,
    required this.baseUrl,
    required this.wsUrl,
    required this.scanUrl,
  });

  final String id;
  final String name;
  final String label;
  final String host;
  final String baseUrl;
  final String wsUrl;
  final String scanUrl;

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'label': label,
        'host': host,
        'baseUrl': baseUrl,
        'wsUrl': wsUrl,
        'scanUrl': scanUrl,
      };

  factory LineConfig.fromJson(Map<String, dynamic> json) {
    return LineConfig(
      id: (json['id'] ?? json['lineKey'] ?? '').toString(),
      name: (json['name'] ?? '').toString(),
      label: (json['label'] ?? '').toString(),
      host: (json['host'] ?? '').toString(),
      baseUrl: (json['baseUrl'] ?? '').toString(),
      wsUrl: (json['wsUrl'] ?? '').toString(),
      scanUrl: (json['scanUrl'] ?? '').toString(),
    );
  }
}

const String kLineStorageKey = 'app_line_id';

const kAppEnv = String.fromEnvironment('APP_ENV', defaultValue: 'prod');
/// Bump when package builtin seeds change so cold clients re-pull /line/config.
const kLineConfigVersion = '2026-07-31-prod-403';

/// Prod enabled line ids: cold-start / auth probe preferred pool (rest are fallback seeds).
const Set<String> kPreferredBuiltinLineIds = {
  'line46',
  'line48',
  'line49',
  'line50',
  'line51',
  'line52',
  'line54',
  'line55',
  'line56',
  'line57',
  'line59',
  'line60',
  'line61',
  'line62',
  'line63',
  'line64',
  'line65',
  'line66',
  'line67',
  'line68',
  'line69',
  'line70',
  'line71',
  'line72',
  'line73',
  'line74',
  'line92',
  'line95',
  'line99',
  'line102',
  'line105',
  'line107',
  'line109',
  'line112',
  'line114',
  'line115',
  'line116',
  'line117',
  'line118',
  'line119',
};

bool isPreferredBuiltinLine(String id) =>
    kPreferredBuiltinLineIds.contains(id);

const _prodH5Scan = 'https://kavun.bgznp.com';

LineConfig _prodBuiltin({
  required String id,
  required String name,
  required String label,
  required String host,
  String? scanUrl,
}) =>
    LineConfig(
      id: id,
      name: name,
      label: label,
      host: host,
      baseUrl: 'https://$host/api',
      wsUrl: 'wss://$host/im',
      scanUrl: scanUrl ?? _prodH5Scan,
    );

/// Cold-start seeds: all new prod app_line (line45-line447, 403 hosts; enabled first).
/// Remote /line/config wins; admin-disabled ids drop after remote apply (merge does not re-inject).
final List<LineConfig> kBuiltinProdLines = [
  _prodBuiltin(
    id: 'line46',
    name: '线路46',
    label: 'helix scnjrm',
    host: 'helix.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line48',
    name: '线路48',
    label: 'orion.bgznp.com',
    host: 'orion.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line49',
    name: '线路49',
    label: 'orion.scnjrm.com',
    host: 'orion.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line50',
    name: '线路50',
    label: 'orion.dvdda.com',
    host: 'orion.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line51',
    name: '线路51',
    label: 'quartz.bgznp.com',
    host: 'quartz.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line52',
    name: '线路52',
    label: 'quartz.scnjrm.com',
    host: 'quartz.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line54',
    name: '线路54',
    label: 'prism.bgznp.com',
    host: 'prism.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line55',
    name: '线路55',
    label: 'prism.scnjrm.com',
    host: 'prism.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line56',
    name: '线路56',
    label: 'prism.dvdda.com',
    host: 'prism.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line57',
    name: '线路57',
    label: 'nova.bgznp.com',
    host: 'nova.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line59',
    name: '线路59',
    label: 'nova.dvdda.com',
    host: 'nova.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line60',
    name: '线路60',
    label: 'atlas.bgznp.com',
    host: 'atlas.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line61',
    name: '线路61',
    label: 'atlas.scnjrm.com',
    host: 'atlas.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line62',
    name: '线路62',
    label: 'atlas.dvdda.com',
    host: 'atlas.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line63',
    name: '线路63',
    label: 'cedar.bgznp.com',
    host: 'cedar.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line64',
    name: '线路64',
    label: 'cedar.scnjrm.com',
    host: 'cedar.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line65',
    name: '线路65',
    label: 'cedar.dvdda.com',
    host: 'cedar.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line66',
    name: '线路66',
    label: 'flint.bgznp.com',
    host: 'flint.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line67',
    name: '线路67',
    label: 'flint.scnjrm.com',
    host: 'flint.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line68',
    name: '线路68',
    label: 'flint.dvdda.com',
    host: 'flint.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line69',
    name: '线路69',
    label: 'ember.bgznp.com',
    host: 'ember.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line70',
    name: '线路70',
    label: 'ember.scnjrm.com',
    host: 'ember.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line71',
    name: '线路71',
    label: 'ember.dvdda.com',
    host: 'ember.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line72',
    name: '线路72',
    label: 'coral.bgznp.com',
    host: 'coral.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line73',
    name: '线路73',
    label: 'coral.scnjrm.com',
    host: 'coral.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line74',
    name: '线路74',
    label: 'coral.dvdda.com',
    host: 'coral.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line92',
    name: '线路92',
    label: 'ivory.dvdda.com',
    host: 'ivory.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line95',
    name: '线路95',
    label: 'jade.dvdda.com',
    host: 'jade.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line99',
    name: '线路99',
    label: 'lunar.bgznp.com',
    host: 'lunar.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line102',
    name: '线路102',
    label: 'maple.bgznp.com',
    host: 'maple.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line105',
    name: '线路105',
    label: 'nexus.bgznp.com',
    host: 'nexus.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line107',
    name: '线路107',
    label: 'nexus.dvdda.com',
    host: 'nexus.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line109',
    name: '线路109',
    label: 'oak.scnjrm.com',
    host: 'oak.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line112',
    name: '线路112',
    label: 'pearl.scnjrm.com',
    host: 'pearl.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line114',
    name: '线路114',
    label: 'raven.bgznp.com',
    host: 'raven.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line115',
    name: '线路115',
    label: 'raven.scnjrm.com',
    host: 'raven.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line116',
    name: '线路116',
    label: 'raven.dvdda.com',
    host: 'raven.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line117',
    name: '线路117',
    label: 'sage.bgznp.com',
    host: 'sage.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line118',
    name: '线路118',
    label: 'sage.scnjrm.com',
    host: 'sage.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line119',
    name: '线路119',
    label: 'sage.dvdda.com',
    host: 'sage.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line45',
    name: '线路45',
    label: 'helix bgznp',
    host: 'helix.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line47',
    name: '线路47',
    label: 'helix dvdda',
    host: 'helix.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line53',
    name: '线路53',
    label: 'quartz.dvdda.com',
    host: 'quartz.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line58',
    name: '线路58',
    label: 'nova.scnjrm.com',
    host: 'nova.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line75',
    name: '线路75',
    label: 'delta.bgznp.com',
    host: 'delta.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line76',
    name: '线路76',
    label: 'delta.scnjrm.com',
    host: 'delta.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line77',
    name: '线路77',
    label: 'delta.dvdda.com',
    host: 'delta.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line78',
    name: '线路78',
    label: 'echo.bgznp.com',
    host: 'echo.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line79',
    name: '线路79',
    label: 'echo.scnjrm.com',
    host: 'echo.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line80',
    name: '线路80',
    label: 'echo.dvdda.com',
    host: 'echo.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line81',
    name: '线路81',
    label: 'frost.bgznp.com',
    host: 'frost.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line82',
    name: '线路82',
    label: 'frost.scnjrm.com',
    host: 'frost.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line83',
    name: '线路83',
    label: 'frost.dvdda.com',
    host: 'frost.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line84',
    name: '线路84',
    label: 'glacier.bgznp.com',
    host: 'glacier.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line85',
    name: '线路85',
    label: 'glacier.scnjrm.com',
    host: 'glacier.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line86',
    name: '线路86',
    label: 'glacier.dvdda.com',
    host: 'glacier.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line87',
    name: '线路87',
    label: 'harbor.bgznp.com',
    host: 'harbor.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line88',
    name: '线路88',
    label: 'harbor.scnjrm.com',
    host: 'harbor.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line89',
    name: '线路89',
    label: 'harbor.dvdda.com',
    host: 'harbor.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line90',
    name: '线路90',
    label: 'ivory.bgznp.com',
    host: 'ivory.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line91',
    name: '线路91',
    label: 'ivory.scnjrm.com',
    host: 'ivory.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line93',
    name: '线路93',
    label: 'jade.bgznp.com',
    host: 'jade.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line94',
    name: '线路94',
    label: 'jade.scnjrm.com',
    host: 'jade.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line96',
    name: '线路96',
    label: 'kiln.bgznp.com',
    host: 'kiln.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line97',
    name: '线路97',
    label: 'kiln.scnjrm.com',
    host: 'kiln.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line98',
    name: '线路98',
    label: 'kiln.dvdda.com',
    host: 'kiln.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line100',
    name: '线路100',
    label: 'lunar.scnjrm.com',
    host: 'lunar.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line101',
    name: '线路101',
    label: 'lunar.dvdda.com',
    host: 'lunar.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line103',
    name: '线路103',
    label: 'maple.scnjrm.com',
    host: 'maple.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line104',
    name: '线路104',
    label: 'maple.dvdda.com',
    host: 'maple.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line106',
    name: '线路106',
    label: 'nexus.scnjrm.com',
    host: 'nexus.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line108',
    name: '线路108',
    label: 'oak.bgznp.com',
    host: 'oak.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line110',
    name: '线路110',
    label: 'oak.dvdda.com',
    host: 'oak.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line111',
    name: '线路111',
    label: 'pearl.bgznp.com',
    host: 'pearl.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line113',
    name: '线路113',
    label: 'pearl.dvdda.com',
    host: 'pearl.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line120',
    name: '线路120',
    label: 'tide.bgznp.com',
    host: 'tide.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line121',
    name: '线路121',
    label: 'tide.scnjrm.com',
    host: 'tide.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line122',
    name: '线路122',
    label: 'tide.dvdda.com',
    host: 'tide.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line123',
    name: '线路123',
    label: 'ultra.bgznp.com',
    host: 'ultra.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line124',
    name: '线路124',
    label: 'ultra.scnjrm.com',
    host: 'ultra.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line125',
    name: '线路125',
    label: 'ultra.dvdda.com',
    host: 'ultra.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line126',
    name: '线路126',
    label: 'vapor.bgznp.com',
    host: 'vapor.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line127',
    name: '线路127',
    label: 'vapor.scnjrm.com',
    host: 'vapor.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line128',
    name: '线路128',
    label: 'vapor.dvdda.com',
    host: 'vapor.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line129',
    name: '线路129',
    label: 'willow.bgznp.com',
    host: 'willow.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line130',
    name: '线路130',
    label: 'willow.scnjrm.com',
    host: 'willow.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line131',
    name: '线路131',
    label: 'willow.dvdda.com',
    host: 'willow.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line132',
    name: '线路132',
    label: 'xenon.bgznp.com',
    host: 'xenon.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line133',
    name: '线路133',
    label: 'xenon.scnjrm.com',
    host: 'xenon.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line134',
    name: '线路134',
    label: 'xenon.dvdda.com',
    host: 'xenon.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line135',
    name: '线路135',
    label: 'amber.bgznp.com',
    host: 'amber.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line136',
    name: '线路136',
    label: 'amber.scnjrm.com',
    host: 'amber.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line137',
    name: '线路137',
    label: 'amber.dvdda.com',
    host: 'amber.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line138',
    name: '线路138',
    label: 'bloom.bgznp.com',
    host: 'bloom.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line139',
    name: '线路139',
    label: 'bloom.scnjrm.com',
    host: 'bloom.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line140',
    name: '线路140',
    label: 'bloom.dvdda.com',
    host: 'bloom.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line141',
    name: '线路141',
    label: 'crater.bgznp.com',
    host: 'crater.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line142',
    name: '线路142',
    label: 'crater.scnjrm.com',
    host: 'crater.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line143',
    name: '线路143',
    label: 'crater.dvdda.com',
    host: 'crater.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line144',
    name: '线路144',
    label: 'dusk.bgznp.com',
    host: 'dusk.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line145',
    name: '线路145',
    label: 'dusk.scnjrm.com',
    host: 'dusk.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line146',
    name: '线路146',
    label: 'dusk.dvdda.com',
    host: 'dusk.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line147',
    name: '线路147',
    label: 'eagle.bgznp.com',
    host: 'eagle.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line148',
    name: '线路148',
    label: 'falcon.bgznp.com',
    host: 'falcon.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line149',
    name: '线路149',
    label: 'falcon.scnjrm.com',
    host: 'falcon.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line150',
    name: '线路150',
    label: 'falcon.dvdda.com',
    host: 'falcon.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line151',
    name: '线路151',
    label: 'gamma.bgznp.com',
    host: 'gamma.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line152',
    name: '线路152',
    label: 'gamma.scnjrm.com',
    host: 'gamma.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line153',
    name: '线路153',
    label: 'gamma.dvdda.com',
    host: 'gamma.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line154',
    name: '线路154',
    label: 'horizon.bgznp.com',
    host: 'horizon.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line155',
    name: '线路155',
    label: 'horizon.scnjrm.com',
    host: 'horizon.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line156',
    name: '线路156',
    label: 'horizon.dvdda.com',
    host: 'horizon.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line157',
    name: '线路157',
    label: 'iris.bgznp.com',
    host: 'iris.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line158',
    name: '线路158',
    label: 'iris.scnjrm.com',
    host: 'iris.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line159',
    name: '线路159',
    label: 'iris.dvdda.com',
    host: 'iris.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line160',
    name: '线路160',
    label: 'jasper.bgznp.com',
    host: 'jasper.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line161',
    name: '线路161',
    label: 'jasper.scnjrm.com',
    host: 'jasper.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line162',
    name: '线路162',
    label: 'jasper.dvdda.com',
    host: 'jasper.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line163',
    name: '线路163',
    label: 'keel.bgznp.com',
    host: 'keel.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line164',
    name: '线路164',
    label: 'keel.scnjrm.com',
    host: 'keel.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line165',
    name: '线路165',
    label: 'keel.dvdda.com',
    host: 'keel.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line166',
    name: '线路166',
    label: 'lumen.bgznp.com',
    host: 'lumen.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line167',
    name: '线路167',
    label: 'lumen.scnjrm.com',
    host: 'lumen.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line168',
    name: '线路168',
    label: 'lumen.dvdda.com',
    host: 'lumen.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line169',
    name: '线路169',
    label: 'meadow.bgznp.com',
    host: 'meadow.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line170',
    name: '线路170',
    label: 'meadow.scnjrm.com',
    host: 'meadow.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line171',
    name: '线路171',
    label: 'meadow.dvdda.com',
    host: 'meadow.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line172',
    name: '线路172',
    label: 'nebula.bgznp.com',
    host: 'nebula.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line173',
    name: '线路173',
    label: 'nebula.scnjrm.com',
    host: 'nebula.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line174',
    name: '线路174',
    label: 'nebula.dvdda.com',
    host: 'nebula.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line175',
    name: '线路175',
    label: 'orbit.bgznp.com',
    host: 'orbit.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line176',
    name: '线路176',
    label: 'orbit.scnjrm.com',
    host: 'orbit.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line177',
    name: '线路177',
    label: 'orbit.dvdda.com',
    host: 'orbit.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line178',
    name: '线路178',
    label: 'pinnacle.bgznp.com',
    host: 'pinnacle.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line179',
    name: '线路179',
    label: 'pinnacle.scnjrm.com',
    host: 'pinnacle.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line180',
    name: '线路180',
    label: 'pinnacle.dvdda.com',
    host: 'pinnacle.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line181',
    name: '线路181',
    label: 'ripple.bgznp.com',
    host: 'ripple.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line182',
    name: '线路182',
    label: 'ripple.scnjrm.com',
    host: 'ripple.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line183',
    name: '线路183',
    label: 'ripple.dvdda.com',
    host: 'ripple.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line184',
    name: '线路184',
    label: 'sierra.bgznp.com',
    host: 'sierra.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line185',
    name: '线路185',
    label: 'sierra.scnjrm.com',
    host: 'sierra.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line186',
    name: '线路186',
    label: 'sierra.dvdda.com',
    host: 'sierra.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line187',
    name: '线路187',
    label: 'timber.bgznp.com',
    host: 'timber.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line188',
    name: '线路188',
    label: 'timber.scnjrm.com',
    host: 'timber.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line189',
    name: '线路189',
    label: 'timber.dvdda.com',
    host: 'timber.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line190',
    name: '线路190',
    label: 'umbra.bgznp.com',
    host: 'umbra.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line191',
    name: '线路191',
    label: 'umbra.scnjrm.com',
    host: 'umbra.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line192',
    name: '线路192',
    label: 'umbra.dvdda.com',
    host: 'umbra.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line193',
    name: '线路193',
    label: 'vortex.bgznp.com',
    host: 'vortex.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line194',
    name: '线路194',
    label: 'vortex.scnjrm.com',
    host: 'vortex.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line195',
    name: '线路195',
    label: 'vortex.dvdda.com',
    host: 'vortex.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line196',
    name: '线路196',
    label: 'yarrow.bgznp.com',
    host: 'yarrow.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line197',
    name: '线路197',
    label: 'yarrow.scnjrm.com',
    host: 'yarrow.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line198',
    name: '线路198',
    label: 'yarrow.dvdda.com',
    host: 'yarrow.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line199',
    name: '线路199',
    label: 'zephyr.bgznp.com',
    host: 'zephyr.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line200',
    name: '线路200',
    label: 'zephyr.scnjrm.com',
    host: 'zephyr.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line201',
    name: '线路201',
    label: 'zephyr.dvdda.com',
    host: 'zephyr.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line202',
    name: '线路202',
    label: 'alpine.bgznp.com',
    host: 'alpine.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line203',
    name: '线路203',
    label: 'alpine.scnjrm.com',
    host: 'alpine.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line204',
    name: '线路204',
    label: 'alpine.dvdda.com',
    host: 'alpine.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line205',
    name: '线路205',
    label: 'bay.bgznp.com',
    host: 'bay.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line206',
    name: '线路206',
    label: 'bay.scnjrm.com',
    host: 'bay.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line207',
    name: '线路207',
    label: 'bay.dvdda.com',
    host: 'bay.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line208',
    name: '线路208',
    label: 'cliff.bgznp.com',
    host: 'cliff.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line209',
    name: '线路209',
    label: 'cliff.scnjrm.com',
    host: 'cliff.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line210',
    name: '线路210',
    label: 'cliff.dvdda.com',
    host: 'cliff.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line211',
    name: '线路211',
    label: 'dawn.bgznp.com',
    host: 'dawn.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line212',
    name: '线路212',
    label: 'dawn.scnjrm.com',
    host: 'dawn.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line213',
    name: '线路213',
    label: 'dawn.dvdda.com',
    host: 'dawn.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line214',
    name: '线路214',
    label: 'elm.bgznp.com',
    host: 'elm.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line215',
    name: '线路215',
    label: 'elm.scnjrm.com',
    host: 'elm.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line216',
    name: '线路216',
    label: 'elm.dvdda.com',
    host: 'elm.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line217',
    name: '线路217',
    label: 'fjord.bgznp.com',
    host: 'fjord.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line218',
    name: '线路218',
    label: 'fjord.scnjrm.com',
    host: 'fjord.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line219',
    name: '线路219',
    label: 'fjord.dvdda.com',
    host: 'fjord.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line220',
    name: '线路220',
    label: 'gulf.bgznp.com',
    host: 'gulf.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line221',
    name: '线路221',
    label: 'gulf.scnjrm.com',
    host: 'gulf.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line222',
    name: '线路222',
    label: 'gulf.dvdda.com',
    host: 'gulf.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line223',
    name: '线路223',
    label: 'hill.bgznp.com',
    host: 'hill.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line224',
    name: '线路224',
    label: 'hill.scnjrm.com',
    host: 'hill.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line225',
    name: '线路225',
    label: 'hill.dvdda.com',
    host: 'hill.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line226',
    name: '线路226',
    label: 'isle.bgznp.com',
    host: 'isle.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line227',
    name: '线路227',
    label: 'isle.scnjrm.com',
    host: 'isle.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line228',
    name: '线路228',
    label: 'isle.dvdda.com',
    host: 'isle.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line229',
    name: '线路229',
    label: 'jet.bgznp.com',
    host: 'jet.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line230',
    name: '线路230',
    label: 'jet.scnjrm.com',
    host: 'jet.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line231',
    name: '线路231',
    label: 'jet.dvdda.com',
    host: 'jet.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line232',
    name: '线路232',
    label: 'key.bgznp.com',
    host: 'key.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line233',
    name: '线路233',
    label: 'key.scnjrm.com',
    host: 'key.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line234',
    name: '线路234',
    label: 'key.dvdda.com',
    host: 'key.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line235',
    name: '线路235',
    label: 'lagoon.bgznp.com',
    host: 'lagoon.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line236',
    name: '线路236',
    label: 'lagoon.scnjrm.com',
    host: 'lagoon.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line237',
    name: '线路237',
    label: 'lagoon.dvdda.com',
    host: 'lagoon.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line238',
    name: '线路238',
    label: 'mesa.bgznp.com',
    host: 'mesa.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line239',
    name: '线路239',
    label: 'mesa.scnjrm.com',
    host: 'mesa.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line240',
    name: '线路240',
    label: 'mesa.dvdda.com',
    host: 'mesa.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line241',
    name: '线路241',
    label: 'nest.bgznp.com',
    host: 'nest.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line242',
    name: '线路242',
    label: 'nest.scnjrm.com',
    host: 'nest.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line243',
    name: '线路243',
    label: 'nest.dvdda.com',
    host: 'nest.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line244',
    name: '线路244',
    label: 'olive.bgznp.com',
    host: 'olive.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line245',
    name: '线路245',
    label: 'olive.scnjrm.com',
    host: 'olive.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line246',
    name: '线路246',
    label: 'olive.dvdda.com',
    host: 'olive.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line247',
    name: '线路247',
    label: 'peak.bgznp.com',
    host: 'peak.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line248',
    name: '线路248',
    label: 'peak.scnjrm.com',
    host: 'peak.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line249',
    name: '线路249',
    label: 'peak.dvdda.com',
    host: 'peak.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line250',
    name: '线路250',
    label: 'quay.bgznp.com',
    host: 'quay.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line251',
    name: '线路251',
    label: 'quay.scnjrm.com',
    host: 'quay.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line252',
    name: '线路252',
    label: 'quay.dvdda.com',
    host: 'quay.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line253',
    name: '线路253',
    label: 'reef.bgznp.com',
    host: 'reef.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line254',
    name: '线路254',
    label: 'reef.scnjrm.com',
    host: 'reef.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line255',
    name: '线路255',
    label: 'reef.dvdda.com',
    host: 'reef.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line256',
    name: '线路256',
    label: 'summit.bgznp.com',
    host: 'summit.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line257',
    name: '线路257',
    label: 'summit.scnjrm.com',
    host: 'summit.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line258',
    name: '线路258',
    label: 'summit.dvdda.com',
    host: 'summit.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line259',
    name: '线路259',
    label: 'terrace.bgznp.com',
    host: 'terrace.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line260',
    name: '线路260',
    label: 'terrace.scnjrm.com',
    host: 'terrace.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line261',
    name: '线路261',
    label: 'terrace.dvdda.com',
    host: 'terrace.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line262',
    name: '线路262',
    label: 'vale.bgznp.com',
    host: 'vale.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line263',
    name: '线路263',
    label: 'vale.scnjrm.com',
    host: 'vale.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line264',
    name: '线路264',
    label: 'vale.dvdda.com',
    host: 'vale.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line265',
    name: '线路265',
    label: 'wharf.bgznp.com',
    host: 'wharf.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line266',
    name: '线路266',
    label: 'wharf.scnjrm.com',
    host: 'wharf.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line267',
    name: '线路267',
    label: 'wharf.dvdda.com',
    host: 'wharf.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line268',
    name: '线路268',
    label: 'yard.bgznp.com',
    host: 'yard.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line269',
    name: '线路269',
    label: 'yard.scnjrm.com',
    host: 'yard.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line270',
    name: '线路270',
    label: 'yard.dvdda.com',
    host: 'yard.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line271',
    name: '线路271',
    label: 'zone.bgznp.com',
    host: 'zone.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line272',
    name: '线路272',
    label: 'zone.scnjrm.com',
    host: 'zone.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line273',
    name: '线路273',
    label: 'zone.dvdda.com',
    host: 'zone.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line274',
    name: '线路274',
    label: 'aqua.bgznp.com',
    host: 'aqua.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line275',
    name: '线路275',
    label: 'aqua.scnjrm.com',
    host: 'aqua.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line276',
    name: '线路276',
    label: 'aqua.dvdda.com',
    host: 'aqua.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line277',
    name: '线路277',
    label: 'birch.bgznp.com',
    host: 'birch.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line278',
    name: '线路278',
    label: 'birch.scnjrm.com',
    host: 'birch.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line279',
    name: '线路279',
    label: 'birch.dvdda.com',
    host: 'birch.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line280',
    name: '线路280',
    label: 'cove.bgznp.com',
    host: 'cove.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line281',
    name: '线路281',
    label: 'cove.scnjrm.com',
    host: 'cove.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line282',
    name: '线路282',
    label: 'cove.dvdda.com',
    host: 'cove.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line283',
    name: '线路283',
    label: 'dune.bgznp.com',
    host: 'dune.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line284',
    name: '线路284',
    label: 'dune.scnjrm.com',
    host: 'dune.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line285',
    name: '线路285',
    label: 'dune.dvdda.com',
    host: 'dune.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line286',
    name: '线路286',
    label: 'eddy.bgznp.com',
    host: 'eddy.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line287',
    name: '线路287',
    label: 'eddy.scnjrm.com',
    host: 'eddy.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line288',
    name: '线路288',
    label: 'eddy.dvdda.com',
    host: 'eddy.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line289',
    name: '线路289',
    label: 'fern.bgznp.com',
    host: 'fern.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line290',
    name: '线路290',
    label: 'fern.scnjrm.com',
    host: 'fern.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line291',
    name: '线路291',
    label: 'fern.dvdda.com',
    host: 'fern.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line292',
    name: '线路292',
    label: 'grove.bgznp.com',
    host: 'grove.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line293',
    name: '线路293',
    label: 'grove.scnjrm.com',
    host: 'grove.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line294',
    name: '线路294',
    label: 'grove.dvdda.com',
    host: 'grove.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line295',
    name: '线路295',
    label: 'haven.bgznp.com',
    host: 'haven.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line296',
    name: '线路296',
    label: 'haven.scnjrm.com',
    host: 'haven.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line297',
    name: '线路297',
    label: 'haven.dvdda.com',
    host: 'haven.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line298',
    name: '线路298',
    label: 'inlet.bgznp.com',
    host: 'inlet.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line299',
    name: '线路299',
    label: 'inlet.scnjrm.com',
    host: 'inlet.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line300',
    name: '线路300',
    label: 'inlet.dvdda.com',
    host: 'inlet.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line301',
    name: '线路301',
    label: 'jewel.bgznp.com',
    host: 'jewel.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line302',
    name: '线路302',
    label: 'jewel.scnjrm.com',
    host: 'jewel.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line303',
    name: '线路303',
    label: 'jewel.dvdda.com',
    host: 'jewel.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line304',
    name: '线路304',
    label: 'knoll.bgznp.com',
    host: 'knoll.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line305',
    name: '线路305',
    label: 'knoll.scnjrm.com',
    host: 'knoll.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line306',
    name: '线路306',
    label: 'knoll.dvdda.com',
    host: 'knoll.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line307',
    name: '线路307',
    label: 'lotus.bgznp.com',
    host: 'lotus.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line308',
    name: '线路308',
    label: 'lotus.scnjrm.com',
    host: 'lotus.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line309',
    name: '线路309',
    label: 'lotus.dvdda.com',
    host: 'lotus.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line310',
    name: '线路310',
    label: 'mist.bgznp.com',
    host: 'mist.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line311',
    name: '线路311',
    label: 'mist.scnjrm.com',
    host: 'mist.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line312',
    name: '线路312',
    label: 'mist.dvdda.com',
    host: 'mist.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line313',
    name: '线路313',
    label: 'north.bgznp.com',
    host: 'north.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line314',
    name: '线路314',
    label: 'north.scnjrm.com',
    host: 'north.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line315',
    name: '线路315',
    label: 'north.dvdda.com',
    host: 'north.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line316',
    name: '线路316',
    label: 'opus.bgznp.com',
    host: 'opus.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line317',
    name: '线路317',
    label: 'opus.scnjrm.com',
    host: 'opus.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line318',
    name: '线路318',
    label: 'opus.dvdda.com',
    host: 'opus.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line319',
    name: '线路319',
    label: 'pine.bgznp.com',
    host: 'pine.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line320',
    name: '线路320',
    label: 'pine.scnjrm.com',
    host: 'pine.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line321',
    name: '线路321',
    label: 'pine.dvdda.com',
    host: 'pine.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line322',
    name: '线路322',
    label: 'quest.bgznp.com',
    host: 'quest.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line323',
    name: '线路323',
    label: 'quest.scnjrm.com',
    host: 'quest.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line324',
    name: '线路324',
    label: 'quest.dvdda.com',
    host: 'quest.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line325',
    name: '线路325',
    label: 'ridge.bgznp.com',
    host: 'ridge.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line326',
    name: '线路326',
    label: 'ridge.scnjrm.com',
    host: 'ridge.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line327',
    name: '线路327',
    label: 'ridge.dvdda.com',
    host: 'ridge.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line328',
    name: '线路328',
    label: 'storm.bgznp.com',
    host: 'storm.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line329',
    name: '线路329',
    label: 'storm.scnjrm.com',
    host: 'storm.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line330',
    name: '线路330',
    label: 'storm.dvdda.com',
    host: 'storm.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line331',
    name: '线路331',
    label: 'trail.bgznp.com',
    host: 'trail.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line332',
    name: '线路332',
    label: 'trail.scnjrm.com',
    host: 'trail.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line333',
    name: '线路333',
    label: 'trail.dvdda.com',
    host: 'trail.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line334',
    name: '线路334',
    label: 'unity.bgznp.com',
    host: 'unity.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line335',
    name: '线路335',
    label: 'unity.scnjrm.com',
    host: 'unity.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line336',
    name: '线路336',
    label: 'unity.dvdda.com',
    host: 'unity.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line337',
    name: '线路337',
    label: 'vista.bgznp.com',
    host: 'vista.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line338',
    name: '线路338',
    label: 'vista.scnjrm.com',
    host: 'vista.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line339',
    name: '线路339',
    label: 'vista.dvdda.com',
    host: 'vista.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line340',
    name: '线路340',
    label: 'wave.bgznp.com',
    host: 'wave.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line341',
    name: '线路341',
    label: 'wave.scnjrm.com',
    host: 'wave.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line342',
    name: '线路342',
    label: 'wave.dvdda.com',
    host: 'wave.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line343',
    name: '线路343',
    label: 'york.bgznp.com',
    host: 'york.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line344',
    name: '线路344',
    label: 'york.scnjrm.com',
    host: 'york.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line345',
    name: '线路345',
    label: 'york.dvdda.com',
    host: 'york.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line346',
    name: '线路346',
    label: 'zenith.bgznp.com',
    host: 'zenith.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line347',
    name: '线路347',
    label: 'zenith.scnjrm.com',
    host: 'zenith.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line348',
    name: '线路348',
    label: 'zenith.dvdda.com',
    host: 'zenith.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line349',
    name: '线路349',
    label: 'aurora.bgznp.com',
    host: 'aurora.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line350',
    name: '线路350',
    label: 'aurora.scnjrm.com',
    host: 'aurora.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line351',
    name: '线路351',
    label: 'aurora.dvdda.com',
    host: 'aurora.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line352',
    name: '线路352',
    label: 'blaze.bgznp.com',
    host: 'blaze.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line353',
    name: '线路353',
    label: 'blaze.scnjrm.com',
    host: 'blaze.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line354',
    name: '线路354',
    label: 'blaze.dvdda.com',
    host: 'blaze.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line355',
    name: '线路355',
    label: 'comet.bgznp.com',
    host: 'comet.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line356',
    name: '线路356',
    label: 'comet.scnjrm.com',
    host: 'comet.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line357',
    name: '线路357',
    label: 'comet.dvdda.com',
    host: 'comet.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line358',
    name: '线路358',
    label: 'drift.bgznp.com',
    host: 'drift.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line359',
    name: '线路359',
    label: 'drift.scnjrm.com',
    host: 'drift.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line360',
    name: '线路360',
    label: 'drift.dvdda.com',
    host: 'drift.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line361',
    name: '线路361',
    label: 'emberly.bgznp.com',
    host: 'emberly.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line362',
    name: '线路362',
    label: 'emberly.scnjrm.com',
    host: 'emberly.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line363',
    name: '线路363',
    label: 'emberly.dvdda.com',
    host: 'emberly.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line364',
    name: '线路364',
    label: 'flare.bgznp.com',
    host: 'flare.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line365',
    name: '线路365',
    label: 'flare.scnjrm.com',
    host: 'flare.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line366',
    name: '线路366',
    label: 'flare.dvdda.com',
    host: 'flare.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line367',
    name: '线路367',
    label: 'gale.bgznp.com',
    host: 'gale.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line368',
    name: '线路368',
    label: 'gale.scnjrm.com',
    host: 'gale.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line369',
    name: '线路369',
    label: 'gale.dvdda.com',
    host: 'gale.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line370',
    name: '线路370',
    label: 'haze.bgznp.com',
    host: 'haze.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line371',
    name: '线路371',
    label: 'haze.scnjrm.com',
    host: 'haze.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line372',
    name: '线路372',
    label: 'haze.dvdda.com',
    host: 'haze.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line373',
    name: '线路373',
    label: 'ion.bgznp.com',
    host: 'ion.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line374',
    name: '线路374',
    label: 'ion.scnjrm.com',
    host: 'ion.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line375',
    name: '线路375',
    label: 'ion.dvdda.com',
    host: 'ion.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line376',
    name: '线路376',
    label: 'jolt.bgznp.com',
    host: 'jolt.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line377',
    name: '线路377',
    label: 'jolt.scnjrm.com',
    host: 'jolt.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line378',
    name: '线路378',
    label: 'jolt.dvdda.com',
    host: 'jolt.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line379',
    name: '线路379',
    label: 'kite.bgznp.com',
    host: 'kite.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line380',
    name: '线路380',
    label: 'kite.scnjrm.com',
    host: 'kite.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line381',
    name: '线路381',
    label: 'kite.dvdda.com',
    host: 'kite.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line382',
    name: '线路382',
    label: 'lynx.bgznp.com',
    host: 'lynx.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line383',
    name: '线路383',
    label: 'lynx.scnjrm.com',
    host: 'lynx.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line384',
    name: '线路384',
    label: 'lynx.dvdda.com',
    host: 'lynx.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line385',
    name: '线路385',
    label: 'mint.bgznp.com',
    host: 'mint.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line386',
    name: '线路386',
    label: 'mint.scnjrm.com',
    host: 'mint.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line387',
    name: '线路387',
    label: 'mint.dvdda.com',
    host: 'mint.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line388',
    name: '线路388',
    label: 'nimbus.bgznp.com',
    host: 'nimbus.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line389',
    name: '线路389',
    label: 'nimbus.scnjrm.com',
    host: 'nimbus.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line390',
    name: '线路390',
    label: 'nimbus.dvdda.com',
    host: 'nimbus.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line391',
    name: '线路391',
    label: 'onyx.bgznp.com',
    host: 'onyx.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line392',
    name: '线路392',
    label: 'onyx.scnjrm.com',
    host: 'onyx.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line393',
    name: '线路393',
    label: 'onyx.dvdda.com',
    host: 'onyx.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line394',
    name: '线路394',
    label: 'plume.bgznp.com',
    host: 'plume.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line395',
    name: '线路395',
    label: 'plume.scnjrm.com',
    host: 'plume.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line396',
    name: '线路396',
    label: 'plume.dvdda.com',
    host: 'plume.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line397',
    name: '线路397',
    label: 'quartzite.bgznp.com',
    host: 'quartzite.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line398',
    name: '线路398',
    label: 'quartzite.scnjrm.com',
    host: 'quartzite.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line399',
    name: '线路399',
    label: 'quartzite.dvdda.com',
    host: 'quartzite.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line400',
    name: '线路400',
    label: 'rover.bgznp.com',
    host: 'rover.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line401',
    name: '线路401',
    label: 'rover.scnjrm.com',
    host: 'rover.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line402',
    name: '线路402',
    label: 'rover.dvdda.com',
    host: 'rover.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line403',
    name: '线路403',
    label: 'spark.bgznp.com',
    host: 'spark.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line404',
    name: '线路404',
    label: 'spark.scnjrm.com',
    host: 'spark.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line405',
    name: '线路405',
    label: 'spark.dvdda.com',
    host: 'spark.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line406',
    name: '线路406',
    label: 'tundra.bgznp.com',
    host: 'tundra.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line407',
    name: '线路407',
    label: 'tundra.scnjrm.com',
    host: 'tundra.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line408',
    name: '线路408',
    label: 'tundra.dvdda.com',
    host: 'tundra.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line409',
    name: '线路409',
    label: 'umbriel.bgznp.com',
    host: 'umbriel.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line410',
    name: '线路410',
    label: 'umbriel.scnjrm.com',
    host: 'umbriel.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line411',
    name: '线路411',
    label: 'umbriel.dvdda.com',
    host: 'umbriel.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line412',
    name: '线路412',
    label: 'violet.bgznp.com',
    host: 'violet.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line413',
    name: '线路413',
    label: 'violet.scnjrm.com',
    host: 'violet.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line414',
    name: '线路414',
    label: 'violet.dvdda.com',
    host: 'violet.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line415',
    name: '线路415',
    label: 'wisp.bgznp.com',
    host: 'wisp.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line416',
    name: '线路416',
    label: 'wisp.scnjrm.com',
    host: 'wisp.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line417',
    name: '线路417',
    label: 'wisp.dvdda.com',
    host: 'wisp.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line418',
    name: '线路418',
    label: 'xylos.bgznp.com',
    host: 'xylos.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line419',
    name: '线路419',
    label: 'xylos.scnjrm.com',
    host: 'xylos.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line420',
    name: '线路420',
    label: 'xylos.dvdda.com',
    host: 'xylos.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line421',
    name: '线路421',
    label: 'yonder.bgznp.com',
    host: 'yonder.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line422',
    name: '线路422',
    label: 'yonder.scnjrm.com',
    host: 'yonder.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line423',
    name: '线路423',
    label: 'yonder.dvdda.com',
    host: 'yonder.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line424',
    name: '线路424',
    label: 'zircon.bgznp.com',
    host: 'zircon.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line425',
    name: '线路425',
    label: 'zircon.scnjrm.com',
    host: 'zircon.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line426',
    name: '线路426',
    label: 'zircon.dvdda.com',
    host: 'zircon.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line427',
    name: '线路427',
    label: 'anvil.bgznp.com',
    host: 'anvil.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line428',
    name: '线路428',
    label: 'anvil.scnjrm.com',
    host: 'anvil.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line429',
    name: '线路429',
    label: 'anvil.dvdda.com',
    host: 'anvil.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line430',
    name: '线路430',
    label: 'bison.bgznp.com',
    host: 'bison.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line431',
    name: '线路431',
    label: 'bison.scnjrm.com',
    host: 'bison.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line432',
    name: '线路432',
    label: 'bison.dvdda.com',
    host: 'bison.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line433',
    name: '线路433',
    label: 'canyon.bgznp.com',
    host: 'canyon.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line434',
    name: '线路434',
    label: 'canyon.scnjrm.com',
    host: 'canyon.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line435',
    name: '线路435',
    label: 'canyon.dvdda.com',
    host: 'canyon.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line436',
    name: '线路436',
    label: 'dynamo.bgznp.com',
    host: 'dynamo.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line437',
    name: '线路437',
    label: 'dynamo.scnjrm.com',
    host: 'dynamo.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line438',
    name: '线路438',
    label: 'dynamo.dvdda.com',
    host: 'dynamo.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line439',
    name: '线路439',
    label: 'emberon.bgznp.com',
    host: 'emberon.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line440',
    name: '线路440',
    label: 'emberon.scnjrm.com',
    host: 'emberon.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line441',
    name: '线路441',
    label: 'emberon.dvdda.com',
    host: 'emberon.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line442',
    name: '线路442',
    label: 'falx.bgznp.com',
    host: 'falx.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line443',
    name: '线路443',
    label: 'falx.scnjrm.com',
    host: 'falx.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line444',
    name: '线路444',
    label: 'falx.dvdda.com',
    host: 'falx.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line445',
    name: '线路445',
    label: 'glyph.bgznp.com',
    host: 'glyph.bgznp.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line446',
    name: '线路446',
    label: 'glyph.scnjrm.com',
    host: 'glyph.scnjrm.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
  _prodBuiltin(
    id: 'line447',
    name: '线路447',
    label: 'glyph.dvdda.com',
    host: 'glyph.dvdda.com',
    scanUrl: 'https://zenty.scnjrm.com',
  ),
];

LineConfig _testBuiltin({
  required String id,
  required String name,
  required String label,
  required String host,
}) =>
    LineConfig(
      id: id,
      name: name,
      label: label,
      host: host,
      baseUrl: 'https://$host/api',
      wsUrl: 'wss://$host/im',
      scanUrl: 'https://novali.de010.com',
    );

final List<LineConfig> kBuiltinTestLines = [
  _testBuiltin(
    id: 'line1',
    name: '线路1',
    label: 'de010 主线路',
    host: 'kivola.de010.com',
  ),
  _testBuiltin(
    id: 'line2',
    name: '线路2',
    label: 'de010 备用线路1',
    host: 'mexato.de010.com',
  ),
  _testBuiltin(
    id: 'line3',
    name: '线路3',
    label: 'de010 备用线路2',
    host: 'roxani.de010.com',
  ),
  _testBuiltin(
    id: 'line4',
    name: '线路4',
    label: 'de010 备用线路3',
    host: 'setura.de010.com',
  ),
];

List<LineConfig> get kBuiltinProductionLines =>
    kAppEnv == 'test' ? kBuiltinTestLines : kBuiltinProdLines;

const LineConfig kLocalDevLine = LineConfig(
  id: 'line_local',
  name: '本地调试',
  label: '127.0.0.1（adb reverse）',
  host: '127.0.0.1',
  baseUrl: 'http://127.0.0.1:27418',
  wsUrl: 'ws://127.0.0.1:27893/im',
  scanUrl: 'http://127.0.0.1:8080',
);

const String kLocalDevLanHost =
    String.fromEnvironment('LOCAL_DEV_HOST', defaultValue: '');

List<String> get kLocalDevProbeHosts {
  if (kLocalDevLanHost.isEmpty) return const ['127.0.0.1'];
  return ['127.0.0.1', kLocalDevLanHost];
}

LineConfig localDevLineForHost(String host) => LineConfig(
      id: 'line_local',
      name: '本地调试',
      label: '本地 DEV ($host)',
      host: host,
      baseUrl: 'http://$host:27418',
      wsUrl: 'ws://$host:27893/im',
      scanUrl: 'http://$host:8080',
    );

/// Compatibility: runtime overrides via [bindLineRuntime] (LineRepository).
List<LineConfig> Function()? _productionLinesOverride;
List<LineConfig> Function()? _visibleLinesOverride;
LineConfig Function(String?)? _byIdOverride;
LineConfig Function()? _defaultLineOverride;
String Function()? _configVersionOverride;

void bindLineRuntime({
  required List<LineConfig> Function() productionLines,
  required List<LineConfig> Function() visibleLines,
  required LineConfig Function(String?) byId,
  required LineConfig Function() defaultLine,
  required String Function() configVersion,
}) {
  _productionLinesOverride = productionLines;
  _visibleLinesOverride = visibleLines;
  _byIdOverride = byId;
  _defaultLineOverride = defaultLine;
  _configVersionOverride = configVersion;
}

String get effectiveLineConfigVersion =>
    _configVersionOverride?.call() ?? kLineConfigVersion;

/// Runtime production lines (remote cache or builtin).
List<LineConfig> get kProductionLines =>
    _productionLinesOverride?.call() ?? kBuiltinProductionLines;

List<LineConfig> get kLines => kProductionLines;

List<LineConfig> get kVisibleLines =>
    _visibleLinesOverride?.call() ??
    (kDebugMode ? [kLocalDevLine, ...kBuiltinProductionLines] : kBuiltinProductionLines);

LineConfig get kDefaultLine =>
    _defaultLineOverride?.call() ??
    (kDebugMode ? kLocalDevLine : kBuiltinProductionLines.first);

LineConfig lineById(String? id) {
  final override = _byIdOverride;
  if (override != null) return override(id);
  if (id == null) return kDefaultLine;
  if (id == 'line_local' && !kDebugMode) {
    return kBuiltinProductionLines.first;
  }
  for (final line in kVisibleLines) {
    if (line.id == id) return line;
  }
  return kDefaultLine;
}
